# Uncomment this line to define a global platform for your project
platform :ios, "10.0"


target 'rainbow-radio' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rainbow-radio
  pod 'Alamofire',
  :git => 'https://github.com/Alamofire/Alamofire.git',
  :branch => 'swift3'
  
  pod 'RxSwift',
  :git => 'https://github.com/ReactiveX/RxSwift.git',
  :branch => 'master'


end
